//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MicroDrvUI.rc
//
#define IDS_SECTION                     1
#define IDS_CALIBRATED                  2
#define MANIFEST_RESOURCE               2
#define IDS_NAME                        3
#define IDS_DEV_SECTION                 4
#define IDS_DEVICE_SECTION              4
#define IDS_ADV_SECTION                 10
#define IDD_ABOUTBOX                    103
#define IDD_LAYOUT                      104
#define IDD_WATERMARK                   105
#define IDD_FONT                        106
#define IDD_BARCODE                     107
#define IDD_BARCODE_2D                  108
#define IDD_COMMAND                     109
#define IDD_TOOL                        110
#define IDD_OPERATION                   111
#define IDD_CONTROL_FONT                116
#define IDD_CONTROL_FONT_TABLE          117
#define IDD_DOWNLOAD                    118
#define IDD_PDF417                      119
#define IDD_QRCODE                      120
#define IDD_MAXICODE                    121
#define IDD_SETTING                     122
#define IDD_DEBUG                       123
#define IDR_MAINFRAME                   128
#define IDB_LOGO                        202
#define IDB_PORTRAIT                    204
#define IDB_PORTRAIT_R                  205
#define IDB_LANDSCAPE                   206
#define IDB_LANDSCAPE_R                 207
#define IDC_DRIVER_COMMIT               1002
#define IDC_DRIVER_COPYRIGHT            1003
#define IDC_DRIVER_VERSION              1004
#define IDC_DRIVER_NAME                 1005
#define IDC_BEGIN_DOC                   1011
#define IDC_BEGIN_PAGE                  1012
#define IDC_END_PAGE                    1013
#define IDC_END_DOC                     1014
#define IDC_SEND_COMMAND                1015
#define IDC_HEX_COMMAND                 1016
#define IDC_CONVERT2BITMAP              1016
#define IDC_CASH_COMBOX                 1017
#define IDC_CONVERT2JPG                 1017
#define IDC_CONVERT2TIFF                1018
#define IDC_FEED_BACK                   1019
#define IDC_CHECK_UPDATE                1020
#define IDC_CUT_OPTION                  1020
#define IDC_PAPER_SIZE                  1020
#define IDC_BARCODE_FONT_NAME           1020
#define IDC_FEED_PAPER                  1021
#define IDC_FEED_PAPER_SPIN             1022
#define IDC_BARCODE_TYPE                1022
#define IDC_CONVERTOUTPUT               1022
#define IDC_FEED_PAPER_BEFER_CUT        1023
#define IDC_FEED_PAPER_BEFORE_CUT       1023
#define IDC_BARCODE_HRI_POSITION        1023
#define IDC_ERROR_CORRECTION            1023
#define IDC_SENT2PRINTER                1023
#define IDC_BUZZER_COMBOX               1027
#define IDC_LOGO_PRINT                  1028
#define IDC_LOGO_ALIGN_LEFT             1029
#define IDC_WATERMARK_TYPE              1029
#define IDC_LOGO_ALIGN_CENTER           1030
#define IDC_PIINT_POSITION              1030
#define IDC_LOGO_ALIGN_RIGHT            1031
#define IDC_WATERMARK_SIZE_SLIDER       1031
#define IDC_BRIGHTNESS_SLIDER           1032
#define IDC_LOGO_PRINT_BEFORE_CUT       1033
#define IDC_WATERMARK_SIZE              1033
#define IDC_LOGO_PRINT_AFTER_CUT        1034
#define IDC_BRIGHTNESS                  1034
#define IDC_DEFAULT                     1035
#define IDC_PRINT_SELFTEST              1036
#define IDC_FONT_TYPE                   1037
#define IDC_WATERMARK_TEXT              1038
#define IDC_FONT_STYLE                  1039
#define IDC_FONT_SIZE                   1041
#define IDC_ANGLE_SLIDER                1042
#define IDC_ANGLE                       1043
#define IDC_CONTROL_FONT                1045
#define IDC_FEED_PAPER_TEST             1046
#define IDC_CUT_PAPER_TEST              1047
#define IDC_CONTROL_FONT_CHAR           1047
#define IDC_BARCODE_ITEM_WIDTH          1047
#define IDC_CONTROL_FONT_HEX            1048
#define IDC_BARCODE_ITEM_HEIGHT         1048
#define IDC_COLUMN_NUM                  1049
#define IDC_CELL_NUM                    1050
#define IDC_CONTROL_FONT_COMMAND        1052
#define IDC_ZOOM_VALUE                  1052
#define IDC_BARCODE_HEIGHT_MM           1052
#define IDC_EDIT                        1053
#define IDC_BARCODE_ITEM_WIDTH_SPIN     1053
#define IDC_DELETE                      1054
#define IDC_BARCODE_ITEM_HEIGHT_SPIN    1054
#define IDC_CONTROL_FONT_TABLE          1055
#define IDC_BARCODE_HEIGHT_POUND        1055
#define IDC_BROWSER                     1056
#define IDC_COLUMN_NUM_SPIN             1056
#define IDC_DOWNLOAD_FILE               1057
#define IDC_CELL_NUM_SPIN               1057
#define IDC_FILE                        1058
#define IDC_LOG_LIST                    1059
#define IDC_LOG_PREVIEW                 1060
#define IDC_HRI_FONTA                   1060
#define IDC_ADD                         1061
#define IDC_PRINT_AS_BITMAP             1061
#define IDC_HRI_FONTB                   1061
#define IDC_CLEAR_ALL                   1062
#define IDC_DOWNLOAD_ALL                1063
#define IDC_ROTATE_180                  1064
#define IDC_ORIENTATION                 1065
#define IDC_PORTRAIT                    1083
#define IDC_ZOOM                        1084
#define IDC_PRINT_AS_TEXT               1085
#define IDC_ZOOM_SPIN                   1086
#define IDC_LANDSCAPE                   1089
#define IDC_SAVE_FILE                   1727
#define IDC_READ_FILE                   1728
#define IDC_SAVE_AS                     1729
#define IDC_RESTORE_FACTORY_SETTINGS    1731

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
